# Site settings
title: Lancenix - Designer/Developer hybrid
description: "A blog about lorem ipsum ..."
baseurl: "" # for test: remove string '/space-jekyll-template' to ''
url: "" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.github.io'

# User settings
username: lance
user_title: lancenix
# email: lorem.lorem@ipsum.com
# twitter_username: loremipsum
github_username:  lancenix
# gplus_username:  loremipsum
linkedin_public_url: mariajeffina # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
# disqus_username: loremipsum
profile_picture: https://64.media.tumblr.com/90fa0d8d3a7a3a2386ed1ecdbeefebd8/tumblr_okb79lo7A21qk55bko2_500.jpg

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: about me
      url: /about
      key_trigger: 2
    - title: my posts
      url: /posts
      key_trigger: 3
    - title: series
      url: /series
      key_trigger: 4
    - title: tags
      url: /tags
      key_trigger: 5
  section_2:
    - title: github
      url: http://www.github.com/lancenix
      new_tab: true
      key_trigger: g
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: \game\ holoreact → ongoing
    url: https://github.com/lancenix/Holoreact
  - name: \computer vision\ pictify → ongoing
    url: https://gitlab.com/maiesey/pictify
  - name: \ios\ spikap → ongoing
    url: https://github.com/lancenix/spikap
  - name: \game\ pararoom → finished
    url: https://github.com/lancenix/Pararoom
    - name: \game\ senterin → finished
    url: https://github.com/lancenix/Delivery-Guy-Godot

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
